# Generated by Django 5.1.5 on 2025-01-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IllegalDumpingReport',
        ),
    ]
